name: tnplayer
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.2

dependencies:
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  obs_websocket: ^5.2.3
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.0
